sonar.projectKey=iamneo-production-4_6106d8b6-f9f9-4747-b7a0-55f0f250bff2-6e65629a-3bc8-4724-abf7-8308fd00e5a6
sonar.organization=iamneo-production-4
sonar.projectName=React Course Enrollment
sonar.projectVersion=1.0

# Point to your React app source
sonar.sources=reactapp/src

# Exclude node_modules and build
sonar.exclusions=reactapp/node_modules/**,reactapp/build/**
