name: Build and Sonar Scan

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd reactapp
          npm install

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: sqa_bca47d55147cb1b256a213a17c135dfe863be411
          SONAR_HOST_URL: 'https://sonar.server.examly.io'
